# Generated by Django 5.2.16 on 2026-07-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiconversation",
            options={},
        ),
        migrations.RemoveField(
            model_name="aiconversation",
            name="is_archived",
        ),
        migrations.RemoveField(
            model_name="aiconversation",
            name="medical_context",
        ),
        migrations.RemoveField(
            model_name="aiconversation",
            name="messages",
        ),
        migrations.RemoveField(
            model_name="aiconversation",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="aiconversation",
            name="title",
        ),
        migrations.RemoveField(
            model_name="aiconversation",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="message",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="response",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
