# Generated by Django 5.2.16 on 2026-07-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="blood_group",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="profile",
            name="has_anemia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="has_thyroid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="medications",
            field=models.TextField(blank=True),
        ),
    ]
