# Generated by Django 5.2.16 on 2026-07-27 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PCOSProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("irregular_periods", models.BooleanField(default=False)),
                ("acne", models.BooleanField(default=False)),
                ("hair_growth", models.BooleanField(default=False)),
                ("hair_loss", models.BooleanField(default=False)),
                ("weight_changes", models.BooleanField(default=False)),
                ("mood_changes", models.BooleanField(default=False)),
                ("sleep_hours", models.FloatField(default=0)),
                ("water_intake_ml", models.IntegerField(default=0)),
                ("exercise_minutes", models.IntegerField(default=0)),
                ("wellness_score", models.IntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pcos_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
