# Generated by Django 5.2.16 on 2026-07-28 14:56

import apps.authentication.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.authentication.managers.UserManager()),
            ],
        ),
    ]
