# Generated by Django 5.2.16 on 2026-07-25 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_period_start", models.DateField()),
                ("cycle_length_days", models.PositiveSmallIntegerField(default=28)),
                ("period_length_days", models.PositiveSmallIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cycles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CycleEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_date", models.DateField()),
                ("symptoms", models.JSONField(blank=True, default=list)),
                ("pain_level", models.PositiveSmallIntegerField(default=0)),
                (
                    "flow",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("light", "Light"),
                            ("medium", "Medium"),
                            ("heavy", "Heavy"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("energy_level", models.PositiveSmallIntegerField(default=0)),
                (
                    "sleep_hours",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("water_intake_ml", models.PositiveIntegerField(default=0)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="cycles.cycle",
                    ),
                ),
            ],
            options={
                "ordering": ("-entry_date",),
                "unique_together": {("cycle", "entry_date")},
            },
        ),
    ]
