# Generated by Django 5.2.16 on 2026-07-25 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entry_date", models.DateField()),
                ("emoji", models.CharField(max_length=16)),
                (
                    "emotion",
                    models.CharField(
                        choices=[
                            ("very_happy", "Very Happy"),
                            ("happy", "Happy"),
                            ("neutral", "Neutral"),
                            ("low", "Low"),
                            ("anxious", "Anxious"),
                            ("sad", "Sad"),
                        ],
                        default="neutral",
                        max_length=16,
                    ),
                ),
                ("mood_score", models.PositiveSmallIntegerField(default=0)),
                ("stress_level", models.PositiveSmallIntegerField(default=0)),
                ("anxiety_level", models.PositiveSmallIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-entry_date",),
                "unique_together": {("user", "entry_date")},
            },
        ),
    ]
