# Generated by Django 5.2.16 on 2026-07-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_journal_mood"),
        ("mood", "0002_alter_mood_unique_together_remove_mood_user_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mood",
        ),
    ]
