# Generated by Django 5.2.16 on 2026-07-28 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycles", "0001_initial"),
        ("mood", "0003_delete_mood"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="cycle_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mood_entries",
                to="cycles.cycleentry",
            ),
        ),
    ]
