# Generated by Django 5.2.16 on 2026-07-27 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
        ("mood", "0002_alter_mood_unique_together_remove_mood_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="mood",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mood.moodentry",
            ),
        ),
    ]
