# Generated by Django 5.2.16 on 2026-07-28 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_journalentry_delete_journal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="mood",
        ),
    ]
